[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Facundo Olano", email = "facundo.olano@gmail.com"},
]
dependencies = [
    "flask>=2.3.2",
    "feedparser>=6.0.10",
    "favicon>=0.7.0",
    "requests>=2.31.0",
    "sqlalchemy>=2.0.19",
    "flask-sqlalchemy>=3.0.5",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "AGPL"}


[tool.pdm.scripts]
serve = "flask --app src/feedi/app.py run --debug --reload"
feeds = "flask --app src/feedi/app.py feeds"
